Hw05 parallel execution
alexvancasper/otus-go-prof pull request #5
Opened 2023-12-04 14:30 UTC by alexvancasper

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-12-05 11:34 UTC, agneum requested changes
Спасибо за вариант решения.
Хорошая работа, однако есть существенные замечания, поэтому возвращаю на доработку.
Итого: 5 баллов из 10.

2023-12-05 11:34 UTC, agneum commented on hw05_parallel_execution/run.go
> +	job := make(chan Task, n/2)
Почему размер канала `n/2`?

2023-12-05 11:34 UTC, agneum commented on hw05_parallel_execution/run.go
> +			job <- task
Если канал `job` будет заполнен, и код заблокируется на этой строке, то `<-ctx.Done()` обработается только на следующей итерации

2023-12-05 11:34 UTC, agneum commented on hw05_parallel_execution/run.go
> +		time.Sleep(1 * time.Millisecond)
Зачем здесь и ниже используется `Sleep`?

2023-12-05 11:34 UTC, agneum commented on hw05_parallel_execution/run.go
> +		}
Насколько я понимаю, этот бесконечный цикл только проверяет счётчик и постоянно полностью утилизирует 1 CPU.

2023-12-05 11:34 UTC, agneum commented on hw05_parallel_execution/run.go
> +}
В качестве альтерантивы можно использовать пакет atomic - https://pkg.go.dev/sync/atomic

2023-12-05 11:34 UTC, agneum commented on hw05_parallel_execution/run.go
> +var errCount ErrCounter
Глобальная переменная уровня пакета необязятельна, можно перенести в функцию

2023-12-05 19:17 UTC, alexvancasper commented on hw05_parallel_execution/run.go
> +	job := make(chan Task, n/2)
исправил на n по числу воркеров.

2023-12-05 19:23 UTC, alexvancasper commented on hw05_parallel_execution/run.go
> +		time.Sleep(1 * time.Millisecond)
вообще Sleep тут убрать надо было, а добавлял его так как изначально была конструкция for { select {} } чтобы for не съедал весь CPU. В следующем коммите убрал.

2023-12-05 19:30 UTC, alexvancasper commented on hw05_parallel_execution/run.go
> +			job <- task
исправил на case job <- task.

2023-12-05 19:49 UTC, alexvancasper commented on hw05_parallel_execution/run.go
> +		}
Вот здесь как раз имеет смысл добавить sleep?

2023-12-05 19:52 UTC, alexvancasper commented on hw05_parallel_execution/run.go
> +var errCount ErrCounter
убрал в функцию.

2023-12-06 09:55 UTC, agneum commented on hw05_parallel_execution/run.go
> +	job := make(chan Task, n/2)
Почему `n`? :)
Размерности канала = 1 тоже хватит для обработки задач. Т.е как только появляется новая задача в канале, свободный воркер берёт её в работу, и канал освобождается для следующей задачи

2023-12-06 10:03 UTC, alexvancasper commented on hw05_parallel_execution/run.go
> +	job := make(chan Task, n/2)
согласен, 1 более подходящее значение.

2023-12-06 10:03 UTC, agneum commented on hw05_parallel_execution/run.go
> +		time.Sleep(1 * time.Millisecond)
Ок, в данном случае для блокировки цикла я бы не рекомендовал sleep
Лучше основывать решение на свойствах канала при чтении и записи, а именно, учитывать, когда операция блокируется и когда выполняется

2023-12-06 10:06 UTC, agneum approved these changes
Спасибо за правки. Хорошая работа
Итого: 10 баллов из 10. Принято

2023-12-06 10:14 UTC, merged